### ISSUE TITLE
Icons missing on macOS

### ISSUE THREAD

**Issue by ArchdukeTim** [Redux-Robotics/Alchemist#1]
Version 2024.0.1 (2024.0.1)

macOS 14.6.1 

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/32c985d6-1fba-42cd-9083-0bd31a75db55">

**Comment by Eeshwar-Krishnan** [comment]
Thanks for opening this issue!

Seems like its a bug with how things are being compiled onto MacOS. We have a fix in the pipeline for the next minor release of Alchemist.

In the meantime, launching alchemist while connected to the internet should cache some of the icons if that is possible. We will get a fixed build out as soon as we can.

**Comment by Eeshwar-Krishnan** [comment]
Fixed in 2024.3.0
